
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const inter = Inter({ subsets: ["latin"] });
import { TransactionProvider } from "./context/TransactionContext";

export const metadata: Metadata = {
  title: "SendCrypto",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <TransactionProvider>
      <html lang="en">
        <body className=" gradient-bg-welcome" >
          <Navbar />
          {children}
        </body>
      </html>
    </TransactionProvider>
  );
}
